# Generated by Django 3.2.3 on 2021-06-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('dish', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('prep_time', models.IntegerField()),
                ('people', models.IntegerField()),
                ('diet', models.BooleanField()),
            ],
            options={
                'db_table': 'Recipe',
            },
        ),
    ]
