# Generated by Django 3.2.3 on 2021-06-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biekmanRecepten', '0002_recipe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='diet',
        ),
    ]
